# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#title: Your awesome title
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

# Site #整站的基本信息
title: 学习笔记 #网站标题
subtitle: 前端学习笔记 #网站副标题
description: 学习总结 思考感悟 知识管理 #网站描述
author:  zhishan #网站作者，在下方显示
email: zhishan505@gmail.com #联系邮箱
language: zh-CN



baseurl: "/shanBlog" # the subpath of your site, e.g. /blog
encoding: utf-8
url: "https://zhishan33.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  zhishan33

# Build settings
markdown: kramdown
highlighter: rouge

permalink: date
paginate_path: /page:num
#markdown: rdiscount
# Markdown
## https://github.com/chjj/marked
theme: jekyll-theme-cayman
kramdown:
  input: GFM

links1:
  - name:     所有
    url:      /
    type:     recent
    external: false
  - name:     杂集
    url:      /blog/other
    type:     other
    external: false
  - name:     正则
    url:      /blo/reg
    type:     reg
    external: false
  - name:     git
    url:      /blog/git
    type:     git
    external: false
  - name:     css
    url:      /blog/css
    type:     css
    external: false
  - name:     javascript
    url:      /blog/javascript
    type:     javascript
    external: false
blog_1:    recent
blog_2:    other
blog_3:    reg
blog_4:    git
blog_5:    css
blog_6:    javascript

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "zhishan"
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      author: "JS"